components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
pom.xml

Removed dynamic imports and inserted the needed import packages.

IDENTITY-4689: Fixed best practices issues happened when OSGi bundle creation

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/util/AccountUtil.java

Fixed sonar issues

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java

Fixed IDENTITY-6350

---

.travis.yml

Add travis.yaml.

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/exception/AccountLockServiceException.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/internal/AccountServiceComponent.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/internal/AccountServiceDataHolder.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/service/AccountLockService.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/service/AccountLockServiceImpl.java
pom.xml

Resolves https://github.com/wso2/product-is/issues/1944
1. Introduced a new service to validate account lock state, considering the value of account lock claim (http://wso2.org/claims/identity/accountLocked) and account unlock time claim (http://wso2.org/claims/identity/unlockTime).
2. It is expected that when account unlock time out is configured for zero, the account should be locked until it is being unlocked by an admin user. But, the existing logic allows a successful authentication and unlocks the account, when account unlock time out is configured for zero. This issue is fixed by setting the account unlock time only when account unlock time out is configured.

Add account lock service that can be invoked to check account lock state.

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountDisableHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java

- Fixes https://github.com/wso2-extensions/identity-event-handler-account-lock/issues/43
- Also reported in [IDENTITY-7362](https://wso2.org/jira/browse/IDENTITY-7362) UI label grammar correction
ASAP
- None

Fix #43 : [IDENTITY-7362] UI label grammar correction

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java

- step 02 to resolve https://github.com/wso2/product-is/issues/3951
- Improve handlePostAuthentication with a new claim
- Depends on https://github.com/wso2/carbon-identity-framework/pull/1975

Improve handlePostAuthentication method

---

.travis.yml
components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/internal/AccountServiceComponent.java
pom.xml

Change the scr doc comment to component annotation and Update version
environments.]
-

Change the scr doc comment to component annotation and Update version

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
pom.xml

**Proposed changes in this pull request**
- Remove carbon.logging,commons-logging and log4j dependency.
- Add pax-logging dependency
- Remove maven-scr plugin
- Update dependency
**When to merge this PR**
- After identity-framework is updated with log4j2 changes.
- Need to upgrade framework version.

Migrate log4j2 update.

---

features/org.wso2.carbon.identity.handler.event.account.lock.feature/pom.xml
pom.xml

Introduce new version property for the feature compatible version

Introduce new version property for the feature compatible version

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java

Fix https://github.com/wso2/product-is/issues/6778

Improvement to Account Lock/Unlock Event and Email Template

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/internal/AccountServiceComponent.java

Add an error message when account lock handler is not registering properly

Add an error message when account lock handler is not registering properly

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java

Depends on https://github.com/wso2-extensions/identity-governance/pull/380

Move account lock check to post authentication

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountDisableHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java

- Change connector names and categories according to https://github.com/wso2/identity-apps/issues/1007
- Modify connector property names and descriptions for better UX.

Modify connector field names and descriptions, fix minor issues

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java

Claim updates prevented on successful authentication on first try

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AuditConstants.java
pom.xml

add audit log for account lock

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java

Resolves wso2/product-is#9517
In Self registration flow, disable the account unlock mail sending.
1.User self-registration -> Account is locked until user confirms from the email.
2.User receives the account confirmation email.
3.User click the link and confirmation. Now the user account is getting unlocked. Here we triggered the "Account Unlocked" email.
The requirement is to disable the "Account Unlocked" email been triggered during self sign up flow.
-
environments.]
-

Disable Account Unlocked Email during User Signup

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java

Fix comments on :
https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/70

Fix Style issues on PR

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java

> Fix review comments https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/49#discussion_r473192064 and https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/49#discussion_r473192447 in PR: https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/49

Fix review comments

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountDisableHandler.java

overiden the getPriority() method in AccountDisableHandler

Add priority for accountDisableHandler

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountDisableHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AuditConstants.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/util/AccountUtil.java
pom.xml

Added events for account lock/unlock/disable/enable actions.
Fixes wso2/product-is#10365
As soon as possible

Add events and audit logs for lock/unlock/disable/enable

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountDisableHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AuditConstants.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/util/AccountUtil.java
pom.xml

Reverts wso2-extensions/identity-event-handler-account-lock#79 due to test failures in product-is

Revert "Add events and audit logs for lock/unlock/disable/enable"

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/service/AccountLockServiceImpl.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/util/AccountUtil.java

Resolves https://github.com/wso2/product-is/issues/11287

Check account locking enabled in service

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java

Fix sending two emails during the ask password.
When should this PR be merged
After - https://github.com/wso2-extensions/identity-governance/pull/521

Fix sending two emails during ask password.

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java

This PR adds the locked reason to the error code when the account is locked by the administrator. The locked reason is then used to show the error message at the login page when a locked user tries to login.
Related to : https://github.com/wso2/product-is/issues/12355

Add locked reason to the error code when the user account is locked by admin

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/util/AccountUtil.java
pom.xml

$subject
https://github.com/wso2/carbon-kernel/pull/3072

Add account lock by pass enabled check for userstore managers

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
features/org.wso2.carbon.identity.handler.event.account.lock.feature/pom.xml
pom.xml

> Change the version to 1.4.36-SNAPSHOT
> Change the scm tag

Change the version to SNAPSHOT

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountDisableHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java
pom.xml

Adding update fixes
-
environments.]
-

Add update fixes

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
features/org.wso2.carbon.identity.handler.event.account.lock.feature/pom.xml
pom.xml

Bump kernel version

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java

Fix: https://github.com/wso2/product-is/issues/14373
Immediate
N/A

Add facility to disable account lock handler.

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
features/org.wso2.carbon.identity.handler.event.account.lock.feature/pom.xml
pom.xml

Bump version to 1.8.0-SNAPSHOT

Bump version to 1.8.0-SNAPSHOT

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/exception/AccountDisableServiceException.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/internal/AccountServiceComponent.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/service/AccountDisableService.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/service/AccountDisableServiceImpl.java

Adding a new service (`AccountDisableService`) to check on account disabled state. Service will check for the account disabled claim (`http://wso2.org/claims/identity/accountDisabled`) and return the state.
environments.]
-

Add account disable service to check account disabled state

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
features/org.wso2.carbon.identity.handler.event.account.lock.feature/pom.xml
pom.xml

- Refactoring the pom versions to match with the branch.

[1.7.x] Refactoring pom Versions

---

pom.xml

- Updating the goverance version to the latest 1.8.4[1]
[1] https://github.com/wso2-extensions/identity-governance/tree/v1.8.4

Update governance version in account lock handler

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
features/org.wso2.carbon.identity.handler.event.account.lock.feature/pom.xml
pom.xml

The version is updated to major version: 2.0.0 for IPK product.

Update pom to Major Development Version

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/util/AccountUtil.java
pom.xml

Sanitizing PII in Audit Logs

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java

Following things done to improve the performance.
* Move if else to switch cases
* Re arrange code flow
https://github.com/wso2/product-is/issues/14373
Immediate
N/A

Improve code for performance.

---

pom.xml

- Bump carbon identity framework.
Related PR: https://github.com/wso2/carbon-identity-framework/pull/4390

Update carbon identity framework version

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml

Remove carbon.ui dependency

---

pom.xml

Update carbon-identity-framework and identity-governance version range

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java

Describe:
Refactor AccountLockHandler to reduce no of userStoreManager.getUserClaimValues calls.
Resolves https://github.com/wso2/product-is/issues/15850

Refactor AccountLockHandler class no of DB queries

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AuditConstants.java

Issue https://github.com/wso2/product-is/issues/16737
environments.]
-

Add identity claims to audit logs

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
features/org.wso2.carbon.identity.handler.event.account.lock.feature/pom.xml
pom.xml

Changing pom versions for development

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
features/org.wso2.carbon.identity.handler.event.account.lock.feature/pom.xml
pom.xml

Changing snapshot version for next release version

---

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
pom.xml

- $Subject
- https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/97

Send Account Locked/ Unlocked Email when Account Lock On Creation is disabled with Ask Password Flow

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
pom.xml

Resolve the SP-UUID from the thread-local and include it into event property.
- https://github.com/wso2/product-is/issues/20543

Add SP-UUID to event property.

---

.github/workflows/pr-builder.yml
codecov.yml
components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml
features/org.wso2.carbon.identity.handler.event.account.lock.feature/pom.xml
pom.xml

This PR adds Codecov and JaCoCo configurations to the repository.

[Automated]Add Codecov and JaCoCo configurations

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountDisableHandler.java

- Refactor AccountDisableHandler to skip unnecessary processing when the feature is disabled
- Relates to [product-is/issues/7195](https://github.com/wso2/product-is/issues/7195)

Refactor AccountDisableHandler to skip unnecessary processing when the feature is disabled

---

.github/workflows/pr-builder.yml
components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
pom.xml

$subject
- https://github.com/wso2-extensions/identity-oauth2-grant-token-exchange/pull/35

Skip updating account lock claims for token-exchange grant type

---

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java

- Stop showing V1 audit logs when use account is unlocked, if V2 logs are enabled
environments.]
-

Audit log format consolidation
