wso2-extensions/identity-event-handler-account-lock

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountDisableHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/util/AccountUtil.java
Fix for https://github.com/wso2/product-is/issues/5880
Fix for https://github.com/wso2/product-is/issues/5884
Introduced a new state claim(http://wso2.org/claims/accountState) to store the users' state.
If the user is in accountState = "pending" state, that means the user's email is not verified yet. If he is in pending state, the accountLocked email will not be sent.
Locked - If accountLocked is true and accountDisabled is false
Pending_Ask_Password - Ask password email is sent and it is not verifies
Pending_Email_Verification - Email verification is sent and it is not verified yet
Pending_Self_Registration - Self registration mail is sent and it is not verified yet
Disabled - If accountDisabled is true
Unlocked - If an accountDisabled claim is false and the accountLocked claim is false …
=> Fix for sending two emails during user self registration

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/internal/AccountServiceComponent.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/internal/AccountServiceDataHolder.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/util/AccountUtil.java, pom.xml
This pr fixes:  for https://github.com/wso2/product-is/issues/6926
As the fix for https://github.com/wso2/product-is/issues/6778 Following changes were done
Added email templates : accountUnlockAdmin, accountLockAdmin, accountUnlockTimeBased,accountLockFailedAttempt
Removed: accountUnlock, accountLock
wso2-extensions/identity-event-handler-notification#107
Documentation: https://github.com/wso2/docs-is/pull/862/files
to maintain the backward compatibility by this fix it will first look for newly added templates if they do not exist then will check for the removed templates. and will use them for notification triggering
=> Maintain the backward compatibility in changing email templates

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
Fix comments: https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/57
Map returns null if the key does not exists. 
Public issue : https://github.com/wso2/product-is/issues/7346
=> Clear thread local value

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
1. Resolves https://github.com/wso2/product-is/issues/5880
2. Resolves https://github.com/wso2/product-is/issues/8242
- To resolve 1: Do not trigger notifications if the account state is either `PENDING_SELF_REGISTRATION` or `PENDING_EMAIL_VERIFICATION`
- To resolve 2: Removing validating account state for not being empty before sending notifications
=> [FIX] Sending account lock notifications for self registration

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
Resolves: https://github.com/wso2/product-is/issues/8481
Front porting: https://github.com/wso2-support/identity-event-handler-account-lock/pull/30
=> [FIX] Tenant wise email sender config is not working for account locking scenario

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java, pom.xml
> Public fix for https://github.com/wso2/product-is/issues/9708
> https://github.com/wso2/carbon-identity-framework/pull/3197
> https://github.com/wso2-extensions/identity-governance/pull/445
Before merging
=> Add support to enable account lock/unlock notifications during admin forced password reset

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java
Resolves https://github.com/wso2/product-is/issues/10886
Governance level we already handled this \[1]
\[1] https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/handler/LiteUserRegistrationHandler.java#L156
Need to update the document. Created a doc issue \[2]
\[2] https://github.com/wso2/product-is/issues/10914
=> Stop sending account lock email during lite registration

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java, pom.xml
This fix will add the values to the LockedReason claim values to track the locked reason. With this PR, following locked reasons are added.
ADMIN_INITIATED,
MAX_ATTEMPTS_EXCEEDED
PENDING_SELF_REGISTRATION
PENDING_ADMIN_FORCED_USER_PASSWORD_RESET
PENDING_EMAIL_VERIFICATION
PENDING_ASK_PASSWORD
IDLE_ACCOUNT
Related PR: wso2-support/identity-governance#298
Resolves: wso2/product-is#10867
After merging https://github.com/wso2-extensions/identity-governance/pull/472
=> Fix locked reason claim value

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountDisableHandler.java
Resolves https://github.com/wso2/product-is/issues/11277
Related PR - https://github.com/wso2/carbon-identity-framework/pull/3403
This PR is to add post-authentication for AccountDisableHandler such that it can identify account disabled users in the post-authentication flow.
=> Add post authentication for AccountDisableHandler

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
Resolved https://github.com/wso2/product-is/issues/11308
This PR fixes the issue in updating AccountState claim, even when the Internal Notification Management is disabled.
=> Add support to AccountState claim with External Notification Management

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java
This PR fixes the following issues which are mentioned in the related ticket.
Fixes: wso2/product-is#11593
=> Fix forced user password reset state issue

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
Resolves https://github.com/wso2/product-is/issues/11703
With this PR the account unlock time claim is properly cleared for admin-initiated account lock and unlock scenarios.
=> Handle unlock time for ADMIN_INITIATED scenarios

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java, pom.xml
In the current MF authenticators, account lock for failed attempt feature has been implemented inside the authenticator. This PR provides support to use account lock handler to lock user account. 
-  [ ] Merge https://github.com/wso2/carbon-identity-framework/pull/3568
-  [ ] Bump framework version in IS.
=> Implementing account lock for failed login attempts

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
Setting user claims in multiple places resulted in calling the handle event multiple times. This change fixes that.
Refers wso2/product-is#11862
=> Fix POST_ACCOUNT_LOCK triggering twise issue.

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, pom.xml
Improvements related to https://github.com/wso2/carbon-identity-framework/pull/3581. 
This PR handles account locking for authenticators as a different event.
=> Improve account lock handling for authenticators

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java
- Add support for sending notification emails on every lockout cycle based on a new config introduced to the account lock governance connector.
- Add information about the account locked duration to the current notification sent when account is locked due to max failed login attempts.
After https://github.com/wso2/carbon-identity-framework/pull/3604 and https://github.com/wso2/carbon-identity-framework/pull/3604
=> Add support for sending notification emails on every lockout cycle, and add lock duration info to the email

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/service/AccountLockServiceImpl.java
Remove config to enable account lock handler globally, and add a new config to enable account lock on max failed attempts.
Resolves : https://github.com/wso2/product-is/issues/12231
After merging : https://github.com/wso2/carbon-identity-framework/pull/3648
=> Remove config to enable account lock handler globally, and add a new config to enable account lock on max failed attempts

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/service/AccountLockServiceImpl.java
Reverts wso2-extensions/identity-event-handler-account-lock#96
=> Revert "Remove config to enable account lock handler globally, and add a new config to enable account lock on max failed attempts"

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
Related Issues: https://github.com/wso2/product-is/issues/4992
After a successful authentication in first attempt, need to reset `failedLoginAttemptsBeforeSuccess` claim value to 0. Reason for this is, after a few failed logins, user will successfully logged into the application. But when that happen, `failedLoginAttemptsBeforeSuccess` will not be reset to 0. So when the user tries to log next time (first attempt as his last attempt also a success), the  `failedLoginAttemptsBeforeSuccess` is not 0. So when using login based adaptive authentication, the second step will be triggered. (Which is not an expected scenario).
=> Add functionality to reset failed login attempts before success

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/handlers/PostAuthnFailedLockoutClaimHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/internal/AccountServiceComponent.java, pom.xml
A new post authentication handler is introduced to reset the failedLoginLockoutCount claim for authentications coming through the authentication framework. 
The existing reset logic is left as it is with a condition since same post authentication event gets triggered for password grant flow which does not comes through the authentication framework.
=> Introducing new post authentication handler to reset failed login lockout count claim

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java
- Add locked reason to the error code in scenario where account is locked due to exceeding max attempts.
Notes: 
- For the admin initiated scenario, the locked reason has already been added in [1]. 
- In order to preserve existing behaviour, the value for locked reason is defined as a String constant in `AccountLockHandler` class (similar to the approach used in [1]) and used, rather than using the direct string representation of the locked reason claim value.
Resolves: https://github.com/wso2/product-is/issues/15800
[1] https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/101
=> Fix return locked reason query param when max attempts exceeded

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/handlers/PostAuthnFailedLockoutClaimHandler.java
Introduce getAuthenticatedUser method to PostAuthnFailedLockoutClaimHandler.
With this method we can overirde this listner and change  the authenticatedUser object according to the requirements.
=> Introduce getAuthenticatedUser method to PostAuthnFailedLockoutClaimHandler

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
The account lock feature was not working for `custom authenticators`, as the claim retrieval part for `failedLoginAttempts` for a custom authenticator was not included.
Resolves https://github.com/wso2-enterprise/asgardeo-product/issues/17785
Related Issues: https://github.com/wso2/product-is/issues/15850
=> Add missing authenticator specific account lock count claim retrieval.

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/util/AccountUtil.java
For system initiated actions, `loggedInUser` is resolved as `wso2.system.user`. In this case, `getInitiatorId` method returns null since this user is not available in the user store. Added a check to avoid an unnecessary DB call to improve performance
=> Add check for wso2 system username

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java
Change the error description returned for the password grant when maximum failed attempts is reached
Before fix
```
{"error_description":"17003:MaxAttemptsExceeded Error when handling event : POST_AUTHENTICATION","error":"invalid_grant"}
```
After fix
```
{"error_description":"17003 Account is locked for user: amanda in user store: PRIMARY in tenant: carbon.super. Cannot login until the account is unlocked.","error":"invalid_grant"}
```
- https://github.com/wso2/product-is/issues/20266
- https://github.com/wso2-enterprise/wso2-iam-internal/issues/1480
=> Fix max failed attempts exceeded error message for password grant

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java, pom.xml
- Removing `org.wso2.carbon.identity.recovery` dependency since it introduces a circular dependancy. 
- https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/134
=> Remove Identity Recovery Dependency

components/org.wso2.carbon.identity.handler.event.account.lock/pom.xml, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/listener/AccountLockTenantMgtListener.java, pom.xml
- Currently, the system org role is created in sub org creation.
- But this org roles should be shared to sub org when app is sharing with the sub org.
- Hence, from this changes, we are discontinuing the system roles creation on sub org creation.
=> Discontinue System Role Creation for Sub orgs when in Org creation

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java
- With this PR the following changes have been made to ensure the correct sending of the account unlock email.
- At `handlePreSetUserClaimValues()`, previous state of the account is added to thread local properties.
- This previous account state is read and checked before sending account unlock email at `handlePostSetUserClaimValues()` instead of the current account state claim.
=> Check Previous Account State Claim Value before Sending Unlock Email

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/util/AccountUtil.java
This pr provides a configuration that can be used to perform the check for locked user accounts in the pre-authentication handler instead of the default behaviour of performing it in the post-authentication handler. Following configuration can be used for this purpose. 
```
[authentication_policy]
pre_authentication_account_lock_check = true
```
=> Provide configuration to enable pre-authentication locked account check

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java
Fixes https://github.com/wso2/product-is/issues/21207
Need to enable the config:
```
[identity_mgt.user_onboarding]
disable_notify_unlock_state=true
```
=> Disable account unlock notification for user creation with Email Verification Enabled

components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java, components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/constants/AccountConstants.java
To correct the email notification behavior when the account lock policy is set to "Lock account until admin unlocks", ensuring users receive an appropriate message.
* Prevent sending misleading content such as "Please try again after 0 minute(s)" when admin intervention is required to unlock an account.
* Support a new email template (`AccountLockFailedAttemptUntilAdminUnlock`) in such scenarios.
* Add a configuration (`ENABLE_ADMIN_UNLOCK_EMAIL_TEMPLATE_FOR_FAILED_ATTEMPTS`) to control whether the new email template should be applied.
* Maintain backward compatibility and avoid behavioral changes unless the new email template is explicitly added via API.
* Introduced a private utility method `isMaxAttemptsLockWithAdminUnlock()` to determine if the account is locked due to exceeding the …
=> Fix misleading email notification for failed attempt account lock with admin unlock policy
